// <auto-generated />
using System;
using BackendSoftContable.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendSoftContable.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260109002722_impsdobleValorem")]
    partial class impsdobleValorem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BackendSoftContable.Models.ActividadEconomica", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ActividadEconomica");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Ciudad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ciudad");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Colegio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActividadEconomicaId")
                        .HasColumnType("int");

                    b.Property<int>("CiudadId")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IvaRetencion")
                        .HasColumnType("bit");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ManejaAiu")
                        .HasColumnType("bit");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NombreColegio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlanSeleccionado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RegimenIvaId")
                        .HasColumnType("int");

                    b.Property<int>("ResponsabilidadFiscalId")
                        .HasColumnType("int");

                    b.Property<string>("TarifaIca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TributoId")
                        .HasColumnType("int");

                    b.Property<bool?>("UsaDobleImpuesto")
                        .HasColumnType("bit");

                    b.Property<bool?>("usaImpuestoAdValorem")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ActividadEconomicaId");

                    b.HasIndex("CiudadId");

                    b.HasIndex("Nit")
                        .IsUnique();

                    b.HasIndex("RegimenIvaId");

                    b.HasIndex("ResponsabilidadFiscalId");

                    b.HasIndex("TributoId");

                    b.ToTable("Colegios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.RegimenIva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegimenesIva");
                });

            modelBuilder.Entity("BackendSoftContable.Models.ResponsabilidadFiscal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImpuestosRelacionados")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PeriodicidadDeclaracion")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ResponsabilidadFiscal");
                });

            modelBuilder.Entity("BackendSoftContable.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoDian")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Tributo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tributo");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("RepresentanteLegal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ColegioId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NumeroIdentificacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TipoIdentificacionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ColegioId");

                    b.HasIndex("NumeroIdentificacion")
                        .IsUnique();

                    b.HasIndex("TipoIdentificacionId");

                    b.ToTable("RepresentantesLegales");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Colegio", b =>
                {
                    b.HasOne("BackendSoftContable.Models.ActividadEconomica", "ActividadEconomica")
                        .WithMany("Colegios")
                        .HasForeignKey("ActividadEconomicaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSoftContable.Models.Ciudad", "Ciudad")
                        .WithMany("Colegios")
                        .HasForeignKey("CiudadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSoftContable.Models.RegimenIva", "RegimenIva")
                        .WithMany("Colegios")
                        .HasForeignKey("RegimenIvaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSoftContable.Models.ResponsabilidadFiscal", "ResponsabilidadFiscal")
                        .WithMany("Colegios")
                        .HasForeignKey("ResponsabilidadFiscalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSoftContable.Models.Tributo", "Tributo")
                        .WithMany("Colegios")
                        .HasForeignKey("TributoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActividadEconomica");

                    b.Navigation("Ciudad");

                    b.Navigation("RegimenIva");

                    b.Navigation("ResponsabilidadFiscal");

                    b.Navigation("Tributo");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Usuario", b =>
                {
                    b.HasOne("BackendSoftContable.Models.Colegio", "Colegio")
                        .WithMany("Usuarios")
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");
                });

            modelBuilder.Entity("RepresentanteLegal", b =>
                {
                    b.HasOne("BackendSoftContable.Models.Colegio", "Colegio")
                        .WithMany("RepresentantesLegales")
                        .HasForeignKey("ColegioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BackendSoftContable.Models.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Colegio");

                    b.Navigation("TipoIdentificacion");
                });

            modelBuilder.Entity("BackendSoftContable.Models.ActividadEconomica", b =>
                {
                    b.Navigation("Colegios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Ciudad", b =>
                {
                    b.Navigation("Colegios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Colegio", b =>
                {
                    b.Navigation("RepresentantesLegales");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.RegimenIva", b =>
                {
                    b.Navigation("Colegios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.ResponsabilidadFiscal", b =>
                {
                    b.Navigation("Colegios");
                });

            modelBuilder.Entity("BackendSoftContable.Models.Tributo", b =>
                {
                    b.Navigation("Colegios");
                });
#pragma warning restore 612, 618
        }
    }
}
